### PR TITLE
Fix humble packages for darwin platform and add turtlesim example

### PR DESCRIPTION
**Pull request by tanshihaj**
Trying to use this overlay in darwin, and found some missing packages for `humble` distro: `ros2pkg`, `ros2cli`, `ros2run` (but it seems that I added them wrong - according to README.md they autogenerated, but I didn't understand how to add this packages to autogenerator).

Also I've added most simple turtlesim example so people can quickly check if everything works fine.

### CODE REVIEW

**Comment by lopsided98** [comment]
They are not auto-generated because they cannot resolve their dependency on `python3-pytest-timeout`. This package exists in nixpkgs, so it should just be a matter of adding it to rosdep.

**Comment by tanshihaj** [comment]
Where can I find rosdep?

**Comment by tanshihaj** [comment]
https://github.com/ros/rosdistro/pull/34130#pullrequestreview-1072704836 - I've updated rosdep. I only need to make rosdistro sync like in this PR https://github.com/lopsided98/nix-ros-overlay/pull/202, right?

**Comment by lopsided98** [comment]
That runs automatically every Friday, but I just triggered a manual run.

**Pull request closed without merging**
