### PR TITLE
fix: add zeromqt to behaviortree-cpp-v3

### PR DESCRIPTION
**Pull request by mbeutelspacher**
When I try to link against behaviortree-cpp-v3 I get undefined reference errors otherwise even if zeromqt is present in my env

### CODE REVIEW

**Comment by wentasah** [comment]
I don't think this is necessary. The [PR to nixpkgs](https://github.com/NixOS/nixpkgs/pull/224099), which should fix this was just merged. Therefore, once `github:lopsided98/nixpkgs/nix-ros` gets updated, the problem with behaviortree-cpp-v3 (and perhaps also with other packages) will disappear.

**Comment by movefasta** [comment]
if overriding the same in ros1 and ros2 cases better to update [distros/distro-overlay.nix](https://github.com/lopsided98/nix-ros-overlay/blob/master/distros/distro-overlay.nix), that is common for both versions:
https://github.com/lopsided98/nix-ros-overlay/blob/master/distros/distro-overlay.nix#L426-L427

**Comment by lopsided98** [comment]
Can you check whether this is still a problem, and, if so, provide an example package that fails?

**Comment by mbeutelspacher** [comment]
No problem anymore ️❤️

**Pull request closed without merging**
