### PR TITLE
[fix] replace distutils.spawn in sip_configure.py

### PR DESCRIPTION
**Pull request by muellerbernd**
Replace distutils.spawn in sip_configure.py if present. For jazzy this is fixed upstream but for humble not.

### CODE REVIEW

**Comment by wentasah** [comment]
What is this supposed to fix? Building `rosPackages.humble.python-qt-binding` works even without this PR.

Wouldn't it be better to apply the upstream fix? I guess it's [this one](https://github.com/ros-visualization/python_qt_binding/commit/ee4d43bcdb0c5c5d40f81dea3de6185298ab34a7).

**Comment by muellerbernd** [comment]
This fixes building of `qt-gui-cpp`. Thanks for pointing out the upstream fix. I have updated the PR.

**Comment by wentasah** [comment]
This looks better. Probably, the same fix would be needed for noetic and iron, which also fail to build.

I wonder what @lopsided98 prefers. Whether repeating the same code in multiple `distros/*/overrides.nix` (which was being done in the past) or having it once in in `distro-overlay.nix` applied conditionally based on the value of `distro` parameter (which is enabled by a recent patch). I'd say the latter is now preferable.

**Comment by lopsided98** [comment]
I actually prefer copying the code between distros. That way patches for old distros don't stick around after the distro is deleted.

**Pull request merged**
